# Generated by Django 5.0 on 2023-12-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
                ('price', models.CharField(blank=True, default='', max_length=300, verbose_name='Имя')),
            ],
        ),
    ]
